files_not_to_stop = { ...
			'tree_callbacks', ...
			'tree_dependencies', ...
			'bst_get', ...
			'bst_fullfile', ...
			'file_fullpath', ...
			'file_exist', ...
			'bst_fileparts', ...
			'file_compare', ...
			'file_gettype', ...
			'macro_method', ...
			'struct_copy_fields', ...
			'java_create', ...
			'java_call', ...
			'bst_progress', ...
			'db_template',...
			'panel_realtime',...
			'java_setcb',...
			'str_split',...
			'bst_bsxfun',};
    
dbModeOn('toolbox',files_not_to_stop);

