files_not_to_stop = { ...
			'bst_call', ...
			'tree_callbacks', ...
			'tree_dependencies', ...
			'bst_get', ...
			'gui_component', ...
			'bst_fullfile', ...
			'file_fullpath', ...
			'file_exist', ...
			'bst_fileparts', ...
			'file_compare', ...
			'file_gettype', ...
			'macro_method', ...
			'struct_copy_fields', ...
			'java_create', ...
			'java_call', ...
			'bst_progress', ...
			'db_template'};


dbModeOn('toolbox',files_not_to_stop);

